// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xeber.Repository.Concrete.EntityFramework;

namespace Xeber.Migrations
{
    [DbContext(typeof(NewsContext))]
    [Migration("20200218075527_step2")]
    partial class step2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Xeber.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatImg");

                    b.Property<string>("CatName");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Xeber.Entity.Langs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Priority");

                    b.HasKey("Id");

                    b.ToTable("Langs");
                });

            modelBuilder.Entity("Xeber.Entity.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Deleted");

                    b.Property<bool>("IsActiv");

                    b.Property<string>("NewsContent");

                    b.Property<string>("NewsImg");

                    b.Property<string>("NewsTitle");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<int?>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Xeber.Entity.NewsLang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("LangId");

                    b.Property<int?>("LangsId");

                    b.Property<string>("NewsContent");

                    b.Property<int>("NewsId");

                    b.Property<string>("NewsTitle");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<int?>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("LangsId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsLang");
                });

            modelBuilder.Entity("Xeber.Entity.News", b =>
                {
                    b.HasOne("Xeber.Entity.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xeber.Entity.NewsLang", b =>
                {
                    b.HasOne("Xeber.Entity.Langs", "Langs")
                        .WithMany("NewsLang")
                        .HasForeignKey("LangsId");

                    b.HasOne("Xeber.Entity.News", "News")
                        .WithMany("NewsLang")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
